
# PluginLG Main Configuration

# Author Ph1Lou

# Link : https://www.spigotmc.org/resources/loup-garou-uhc.73113/

# Version 1.4

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2019
# Available (en, fr, custom)

lang: fr
autoRoofedMiddle: true
token:
ip:
port:
sendInfoToBotEnable: false


