# WereWolfPlugin Main Configuration

# Author Ph1Lou

# Link : https://www.spigotmc.org/resources/loup-garou-uhc.73113/

# Version 1.8 SNAPSHOT

# You are not allowed to claim this plugin as your own.

# Copyright : All Rights Reserved - 2020-2021
# Available (en, fr)

lang: fr
default_lobby: true

