
# PluginLG Main Configuration

# Author Ph1Lou

# Link : https://www.spigotmc.org/resources/loup-garou-uhc.73113/

# Version 1.4 Snapshot 16

# You are not allowed to alter/decompile/copy the code of this plugin.
# You are not allowed to claim this plugin as your own.

# © All Rights Reserved - 2019
# Available (en, fr, custom)

lang: fr

autoRoofedMiddle: true

