name: WereWolfPlugin
version: "1.6.1"
author: Ph1Lou
main: io.github.ph1lou.werewolfplugin.Main
api-version: "1.16"
load: STARTUP
commands:

  ww:
    description: player commands
  a:
    description: admin commands

