name: pluginLG
version: 1.4
author: Ph1Lou
main: io.github.ph1lou.pluginlg.MainLG
api-version: 1.8
load: STARTUP
commands:

  lg:
    description: commandes des joueurs
    usage: /<command> h
  ww:
    description: commands for players
    usage: /<command> h
  adminWW:
    description: admin commands
    usage: /<command> h

