name: WereWolfPlugin
version: "1.4"
author: Ph1Lou
main: io.github.ph1lou.werewolfplugin.Main
api-version: "1.8"
load: STARTUP
commands:

  ww:
    description: commands for players
    usage: /<command> h
  a:
    description: admin commands
    usage: /<command> h

